// SPDX-License-Identifier: GPL-2.0-or-later
// The declared §15.2 key surface. See wblink/config_registry.h for what this
// table is for and how it is kept honest.
//
// Generated once from the loader's accessor sites and thereafter maintained by
// hand: tests/config_registry_test.py fails the build if it drifts from
// io/src/config.cpp in either direction.
#include "wblink/config_registry.h"

#include <string>

namespace wblink {
namespace {

const KeyEntry kKeys[] = {
    {"adapters",                                  KeyType::kArray},
    {"adapters[].bus",                            KeyType::kString},
    {"adapters[].bw",                             KeyType::kNumber},
    {"adapters[].calib_id",                       KeyType::kString},
    {"adapters[].channel",                        KeyType::kNumber},
    {"adapters[].ifname",                         KeyType::kString},
    {"adapters[].mac",                            KeyType::kString},
    {"adapters[].max_power_qdb",                  KeyType::kNumber},
    {"adapters[].name",                           KeyType::kString},
    {"adapters[].power_map",                      KeyType::kString},
    {"adapters[].power_offset_max_qdb",           KeyType::kNumber},
    {"adapters[].power_offset_qdb",               KeyType::kNumber},
    {"adapters[].power_presets_qdb",              KeyType::kArray},
    {"adapters[].role",                           KeyType::kString},
    {"air",                                       KeyType::kObject},
    {"air.ack_responder",                         KeyType::kBool},
    {"air.airtime_efficiency_permille",           KeyType::kNumber},
    {"air.disable_cca",                           KeyType::kBool},
    {"air.kind",                                  KeyType::kString},
    {"air.ldpc",                                  KeyType::kBool},
    {"air.mcs_probe",                             KeyType::kBool},
    {"air.pace_mbps",                             KeyType::kNumber},
    {"air.rx",                                    KeyType::kArray},
    {"air.rx_drop_permille",                      KeyType::kNumber},
    {"air.stbc",                                  KeyType::kBool},
    {"air.tx",                                    KeyType::kArray},
    {"air.tx_retry_limit",                        KeyType::kNumber},
    {"air.uplink_rate",                           KeyType::kObject},
    {"air.uplink_rate.bw",                        KeyType::kNumber},
    {"air.uplink_rate.mcs",                       KeyType::kNumber},
    {"air.uplink_rate.sgi",                       KeyType::kBool},
    {"air.wedge_exit_windows",                    KeyType::kNumber},
    {"air.wedge_min_submits",                     KeyType::kNumber},
    {"air.wedge_window_ms",                       KeyType::kNumber},
    {"cache",                                     KeyType::kObject},
    {"cache.repair",                              KeyType::kObject},
    {"cache.repair.absolute_symbol_limit",        KeyType::kNumber},
    {"cache.repair.assignment_interval_ms",       KeyType::kNumber},
    {"cache.repair.caches",                       KeyType::kArray},
    {"cache.repair.caches[].endpoint",            KeyType::kString},
    {"cache.repair.caches[].originator",          KeyType::kNumber},
    {"cache.repair.enabled",                      KeyType::kBool},
    {"cache.repair.hard_close_ms",                KeyType::kNumber},
    {"cache.repair.health_floor_permille",        KeyType::kNumber},
    {"cache.repair.listen",                       KeyType::kString},
    {"cache.repair.local_quiet_ms",               KeyType::kNumber},
    {"cache.repair.max_cache_attempts",           KeyType::kNumber},
    {"cache.repair.min_collect_ms",               KeyType::kNumber},
    {"cache.repair.nack_grace_ms",                KeyType::kNumber},
    {"cache.repair.repair_fraction_permille",     KeyType::kNumber},
    {"cache.repair.reply_limit",                  KeyType::kNumber},
    {"cache.repair.request_timeout_ms",           KeyType::kNumber},
    {"cache.repair.status_timeout_ms",            KeyType::kNumber},
    {"cache.repair.stream_id",                    KeyType::kNumber},
    {"cache.repair.tail_grace_ms",                KeyType::kNumber},
    {"cache.store",                               KeyType::kObject},
    {"cache.store.blocks",                        KeyType::kNumber},
    {"cache.store.controller",                    KeyType::kObject},
    {"cache.store.controller.endpoint",           KeyType::kString},
    {"cache.store.controller.originator",         KeyType::kNumber},
    {"cache.store.enabled",                       KeyType::kBool},
    {"cache.store.listen",                        KeyType::kString},
    {"cache.store.max_requests_per_s",            KeyType::kNumber},
    {"cache.store.reply_limit",                   KeyType::kNumber},
    {"cache.store.status_interval_ms",            KeyType::kNumber},
    {"cache.store.status_to",                     KeyType::kArray},
    {"cache.store.stream_ids",                    KeyType::kArray},
    {"control",                                   KeyType::kObject},
    {"control.bind",                              KeyType::kString},
    {"loopback",                                  KeyType::kObject},
    {"loopback.adapters",                         KeyType::kNumber},
    {"loopback.correlation",                      KeyType::kNumber},
    {"loopback.loss",                             KeyType::kObject},
    {"loopback.loss.ge",                          KeyType::kObject},
    {"loopback.loss.ge.loss_b",                   KeyType::kNumber},
    {"loopback.loss.ge.loss_g",                   KeyType::kNumber},
    {"loopback.loss.ge.p_bg",                     KeyType::kNumber},
    {"loopback.loss.ge.p_gb",                     KeyType::kNumber},
    {"loopback.loss.uniform_p",                   KeyType::kNumber},
    {"loopback.return_loss_p",                    KeyType::kNumber},
    {"loopback.rssi_dbm",                         KeyType::kNumber},
    {"loopback.rssi_fade",                        KeyType::kObject},
    {"loopback.rssi_fade.dbm",                    KeyType::kNumber},
    {"loopback.rssi_fade.end_ms",                 KeyType::kNumber},
    {"loopback.rssi_fade.start_ms",               KeyType::kNumber},
    {"loopback.seed",                             KeyType::kNumber},
    {"node",                                      KeyType::kObject},
    {"node.net_id",                               KeyType::kNumber},
    {"node.originator",                           KeyType::kNumber},
    {"node.preferred_originator",                 KeyType::kNumber},
    {"node.recovery_on_latch",                    KeyType::kBool},
    {"node.role",                                 KeyType::kString},
    {"node.spectator",                            KeyType::kBool},
    {"policy",                                    KeyType::kObject},
    {"policy.arq",                                KeyType::kObject},
    {"policy.arq.airtime_frac",                   KeyType::kNumber},
    {"policy.arq.arq_max_fps",                    KeyType::kNumber},
    {"policy.arq.attempt_cap",                    KeyType::kNumber},
    {"policy.arq.budget_floor_bytes",             KeyType::kNumber},
    {"policy.arq.budget_interval_ms",             KeyType::kNumber},
    {"policy.arq.classifier_size_threshold",      KeyType::kNumber},
    {"policy.arq.fwd_clamp_blocks",               KeyType::kNumber},
    {"policy.arq.holddown_ms",                    KeyType::kNumber},
    {"policy.arq.max_block_pkts",                 KeyType::kNumber},
    {"policy.arq.min_recoverable_ms",             KeyType::kNumber},
    {"policy.arq.release_timeout_ms",             KeyType::kNumber},
    {"policy.arq.ring_byte_budget",               KeyType::kNumber},
    {"policy.arq.ring_window_ms",                 KeyType::kNumber},
    {"policy.calibration",                        KeyType::kObject},
    {"policy.calibration.artifact_dir",           KeyType::kString},
    {"policy.calibration.dwell_probe_frames",     KeyType::kNumber},
    {"policy.calibration.dwell_verify_frames",    KeyType::kNumber},
    {"policy.calibration.feed_quiet_ms",          KeyType::kNumber},
    {"policy.calibration.hard_cap_ms",            KeyType::kNumber},
    {"policy.calibration.loss_bad_milli",         KeyType::kNumber},
    {"policy.calibration.loss_ok_milli",          KeyType::kNumber},
    {"policy.calibration.max_qdb",                KeyType::kNumber},
    {"policy.calibration.min_qdb",                KeyType::kNumber},
    {"policy.calibration.offset_seek_step_qdb",   KeyType::kNumber},
    {"policy.calibration.probe_pace_us",          KeyType::kNumber},
    {"policy.calibration.rssi_guard_dbm",         KeyType::kNumber},
    {"policy.calibration.seek_step_qdb",          KeyType::kNumber},
    {"policy.calibration.settle_ms",              KeyType::kNumber},
    {"policy.calibration.tally_retries",          KeyType::kNumber},
    {"policy.calibration.tally_wait_ms",          KeyType::kNumber},
    {"policy.cmd",                                KeyType::kObject},
    {"policy.cmd.ack_timeout_ms",                 KeyType::kNumber},
    {"policy.cmd.copies",                         KeyType::kNumber},
    {"policy.cmd.copy_interval_ms",               KeyType::kNumber},
    {"policy.cmd.echo_copies",                    KeyType::kNumber},
    {"policy.cmd.min_interval_ms",                KeyType::kNumber},
    {"policy.cmd.retry_cap",                      KeyType::kNumber},
    {"policy.csa",                                KeyType::kObject},
    {"policy.csa.ack_timeout_ms",                 KeyType::kNumber},
    {"policy.csa.bind_release_s",                 KeyType::kNumber},
    {"policy.csa.channel_allowlist",              KeyType::kArray},
    {"policy.csa.home_chan",                      KeyType::kNumber},
    {"policy.csa.min_interval_s",                 KeyType::kNumber},
    {"policy.csa.persist_channel",                KeyType::kBool},
    {"policy.csa.psk",                            KeyType::kString},
    {"policy.csa.rx_liveness_ms",                 KeyType::kNumber},
    {"policy.csa.settle_s",                       KeyType::kNumber},
    {"policy.csa.verify_timeout_ms",              KeyType::kNumber},
    {"policy.fec",                                KeyType::kObject},
    {"policy.fec.overhead_frac",                  KeyType::kNumber},
    {"policy.fec.scheme",                         KeyType::kString},
    {"policy.report_hz",                          KeyType::kNumber},
    {"policy.report_timeout_ms",                  KeyType::kNumber},
    {"policy.return",                             KeyType::kObject},
    {"policy.return.guard_us",                    KeyType::kNumber},
    {"policy.return.quiet_gap",                   KeyType::kBool},
    {"policy.return.report_redundancy",           KeyType::kNumber},
    {"policy.return.return_window_us",            KeyType::kNumber},
    {"policy.return.unicast",                     KeyType::kBool},
    {"policy.rx",                                 KeyType::kObject},
    {"policy.rx.admit_n",                         KeyType::kNumber},
    {"policy.rx.admit_window_ms",                 KeyType::kNumber},
    {"policy.rx.clamp_resync_ms",                 KeyType::kNumber},
    {"policy.rx.dwell_ceiling_ms",                KeyType::kNumber},
    {"policy.rx.fwd_clamp_pkts",                  KeyType::kNumber},
    {"policy.rx.idle_teardown_ms",                KeyType::kNumber},
    {"policy.rx.renack_attempts",                 KeyType::kNumber},
    {"policy.rx.renack_backoff_ms",               KeyType::kNumber},
    {"policy.rx.stall_timeout_ms",                KeyType::kNumber},
    {"policy.select",                             KeyType::kObject},
    {"policy.select.bitrate_lead_s",              KeyType::kNumber},
    {"policy.select.demote_milli",                KeyType::kNumber},
    {"policy.select.down_cooldown_s",             KeyType::kNumber},
    {"policy.select.emergency_loss_milli",        KeyType::kNumber},
    {"policy.select.ewma_alpha",                  KeyType::kNumber},
    {"policy.select.failsafe_hold_s",             KeyType::kNumber},
    {"policy.select.failsafe_step_s",             KeyType::kNumber},
    {"policy.select.flap_freeze_count",           KeyType::kNumber},
    {"policy.select.flap_freeze_s",               KeyType::kNumber},
    {"policy.select.flap_freeze_window_s",        KeyType::kNumber},
    {"policy.select.loss_min_uniq",               KeyType::kNumber},
    {"policy.select.loss_persist_score",          KeyType::kNumber},
    {"policy.select.max_profile",                 KeyType::kNumber},
    {"policy.select.mcs_settle_s",                KeyType::kNumber},
    {"policy.select.mcs_up_grace_s",              KeyType::kNumber},
    {"policy.select.min_profile",                 KeyType::kNumber},
    {"policy.select.pressure_escape_s",           KeyType::kNumber},
    {"policy.select.probe_veto_permille",         KeyType::kNumber},
    {"policy.select.probe_veto_ttl_s",            KeyType::kNumber},
    {"policy.select.promote_dwell_s",             KeyType::kNumber},
    {"policy.select.promote_rssi_hyst_db",        KeyType::kNumber},
    {"policy.select.reentry_backoff_s",           KeyType::kNumber},
    {"policy.select.reentry_dwell_s",             KeyType::kNumber},
    {"policy.select.rssi_fade_arm_dbm",           KeyType::kNumber},
    {"policy.select.rssi_fade_db_per_s",          KeyType::kNumber},
    {"policy.select.rssi_floor_dbm",              KeyType::kNumber},
    {"policy.select.rung_lockout_latch_count",    KeyType::kNumber},
    {"policy.select.rung_lockout_s",              KeyType::kNumber},
    {"policy.select.rung_rssi_floor_dbm",         KeyType::kArray},
    {"policy.select.verdict_ttl_s",               KeyType::kNumber},
    {"profile_table",                             KeyType::kString},
    {"scout",                                     KeyType::kObject},
    {"scout.channels",                            KeyType::kArray},
    {"scout.dwell_ms",                            KeyType::kNumber},
    {"stats",                                     KeyType::kObject},
    {"stats.bind",                                KeyType::kObject},
    {"stats.bind.kind",                           KeyType::kString},
    {"stats.bind.listen",                         KeyType::kString},
    {"stats.bind.name",                           KeyType::kString},
    {"stats.bind.send",                           KeyType::kString},
    {"stats.hz",                                  KeyType::kNumber},
    {"stats.stdout",                              KeyType::kBool},
    {"streams",                                   KeyType::kArray},
    {"streams[].arq_mode",                        KeyType::kString},
    {"streams[].bind",                            KeyType::kObject},
    {"streams[].bind.kind",                       KeyType::kString},
    {"streams[].bind.listen",                     KeyType::kString},
    {"streams[].bind.name",                       KeyType::kString},
    {"streams[].bind.send",                       KeyType::kString},
    {"streams[].classifier",                      KeyType::kString},
    {"streams[].dir",                             KeyType::kString},
    {"streams[].fec",                             KeyType::kObject},
    {"streams[].fec.e_rate_permille",             KeyType::kNumber},
    {"streams[].fec.i_rate_permille",             KeyType::kNumber},
    {"streams[].fec.min_k",                       KeyType::kNumber},
    {"streams[].fec.min_r",                       KeyType::kNumber},
    {"streams[].fec.p_rate_permille",             KeyType::kNumber},
    {"streams[].fec.scheme",                      KeyType::kString},
    {"streams[].jscc_shadow",                     KeyType::kObject},
    {"streams[].jscc_shadow.arq_guard_us",        KeyType::kNumber},
    {"streams[].jscc_shadow.enforce",             KeyType::kBool},
    {"streams[].jscc_shadow.fec_cap_permille",    KeyType::kNumber},
    {"streams[].jscc_shadow.fec_floor_permille",  KeyType::kNumber},
    {"streams[].jscc_shadow.feedback_timeout_ms", KeyType::kNumber},
    {"streams[].jscc_shadow.min_rtt_samples",     KeyType::kNumber},
    {"streams[].originator",                      KeyType::kNumber},
    {"streams[].stream_id",                       KeyType::kNumber},
    {"streams[].stream_type",                     KeyType::kStringOrNumber},
    {"venc",                                      KeyType::kObject},
    {"venc.active_mode",                          KeyType::kString},
    {"venc.cap_ceiling_bytes",                    KeyType::kNumber},
    {"venc.command_presets",                      KeyType::kObject},
    {"venc.command_presets.fps",                  KeyType::kArray},
    {"venc.command_presets.framing",              KeyType::kArray},
    {"venc.command_presets.resolution",           KeyType::kArray},
    {"venc.enabled",                              KeyType::kBool},
    {"venc.fps_hint",                             KeyType::kNumber},
    {"venc.fps_ladder",                           KeyType::kObject},
    {"venc.fps_ladder.enabled",                   KeyType::kBool},
    {"venc.fps_ladder.max",                       KeyType::kNumber},
    {"venc.fps_ladder.min",                       KeyType::kNumber},
    {"venc.fps_ladder.min_p_frame_bytes",         KeyType::kNumber},
    {"venc.fps_ladder.preferred",                 KeyType::kNumber},
    {"venc.fps_ladder.reduce_after_ms",           KeyType::kNumber},
    {"venc.fps_ladder.reduce_dwell_ms",           KeyType::kNumber},
    {"venc.fps_ladder.restore_after_ms",          KeyType::kNumber},
    {"venc.fps_ladder.restore_hysteresis_bytes",  KeyType::kNumber},
    {"venc.fps_ladder.sample_timeout_ms",         KeyType::kNumber},
    {"venc.fps_ladder.settle_ms",                 KeyType::kNumber},
    {"venc.frame_caps",                           KeyType::kBool},
    {"venc.host",                                 KeyType::kString},
    {"venc.i_headroom_permille",                  KeyType::kNumber},
    {"venc.max_bitrate_kbps",                     KeyType::kNumber},
    {"venc.mode_apply_cmd",                       KeyType::kString},
    {"venc.modes_dir",                            KeyType::kString},
    {"venc.p_headroom_permille",                  KeyType::kNumber},
    {"venc.recovery_enabled",                     KeyType::kBool},
    {"venc.settle_ms",                            KeyType::kNumber},
};

const char* type_name(KeyType t) {
    switch (t) {
        case KeyType::kObject:         return "object";
        case KeyType::kArray:          return "array";
        case KeyType::kString:         return "string";
        case KeyType::kNumber:         return "number";
        case KeyType::kBool:           return "bool";
        case KeyType::kStringOrNumber: return "string|number";
    }
    return "?";
}

}  // namespace

const KeyEntry* config_registry(std::size_t* count) {
    if (count != nullptr) {
        *count = sizeof(kKeys) / sizeof(kKeys[0]);
    }
    return kKeys;
}

std::string config_schema_json() {
    std::size_t n = 0;
    const KeyEntry* keys = config_registry(&n);
    // Hand-rolled rather than nlohmann: the output is a golden file, so the
    // exact byte layout is the contract and is easier to pin here than to
    // depend on a serialiser's formatting staying put across a vendor bump.
    std::string out = "{\n  \"version\": 1,\n  \"keys\": [\n";
    for (std::size_t i = 0; i < n; ++i) {
        out += "    {\"path\": \"";
        out += keys[i].path;
        out += "\", \"type\": \"";
        out += type_name(keys[i].type);
        out += "\"}";
        if (i + 1 < n) out += ",";
        out += "\n";
    }
    out += "  ]\n}\n";
    return out;
}

}  // namespace wblink
